kind: pipeline
name: default

steps:
- name: test
  image: arduino/arduino-cli:drone-0.0.3
  commands:
    # Check if the Go code is properly formatted and run the linter
    - task check
    # Ensure protobufs compile
    - task protoc
    # Build and test
    - task build
    - task test
    - task test-legacy