version: '2'

tasks:
  protoc:
    desc: Compile protobuf definitions
    cmds:
      - protoc --proto_path=. --go_out=plugins=grpc,paths=source_relative:./proto-gen ./commands/rpc_v1/commands.proto
      - protoc --proto_path=. --go_out=plugins=grpc,paths=source_relative:./proto-gen ./commands/rpc_v1/types.proto
      - protoc --proto_path=. --go_out=plugins=grpc,paths=source_relative:./proto-gen ./commands/rpc_v1/compile.proto

  build:
    desc: Build the project
    cmds:
      - go build -v -i

  test:
    desc: Run the full testsuite
    cmds:
      - task: test-unit
      - task: test-integration

  test-unit:
    desc: Run unit tests only
    cmds:
      - go test -short {{ default "-v" .GOFLAGS }} {{ default "./..." .TARGETS }}

  test-integration:
    desc: Run integration tests only
    cmds:
      - go test -run Integration {{ default "-v" .GOFLAGS }} {{ default "./..." .TARGETS }}
